# Generated by Django 5.0.6 on 2024-08-12 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voting", "0002_menu_menu_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menu",
            name="menu_name",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
