# Generated by Django 5.0.6 on 2024-08-12 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voting", "0003_alter_menu_menu_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vote",
            name="vote_time",
            field=models.DateField(auto_now_add=True),
        ),
    ]
