# Generated by Django 5.0.6 on 2024-08-12 12:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("voting", "0004_alter_vote_vote_time"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="vote",
            unique_together={("user", "menu", "vote_time")},
        ),
    ]
